#ifndef QTCDEVPLUGIN_GLOBAL_H
#define QTCDEVPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(QTCDEVPLUGIN_LIBRARY)
#  define QTCDEVPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define QTCDEVPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCDEVPLUGIN_GLOBAL_H
