#ifndef QTCPLUGINTEST_GLOBAL_H
#define QTCPLUGINTEST_GLOBAL_H

#include <QtGlobal>

#if defined(QTCPLUGINTEST_LIBRARY)
#  define QTCPLUGINTESTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTCPLUGINTESTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTCPLUGINTEST_GLOBAL_H
